version: '3'
services:
  textract-api.test:
    build:
      context: ../packages/textract-laravel/vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        NODE_VERSION: 18
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${APP_DOMAIN}:host-gateway'
    ports:
      - '${MAIN_PORT:-8080}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '../packages/textract-laravel:/var/www/html'
      - '../packages/textract-core:/var/www/textract-core'
      - '../packages/textract-routing:/var/www/textract-routing'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - mailpit
      - rabbitmq
    links:
      - rabbitmq
      - mysql
      - redis
  textract-api.queue:
    build:
      context: ../packages/textract-laravel/vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        NODE_VERSION: 18
    image: sail-8.3/app
    command: ["bash", "-c", "php artisan rabbitmq:consume --queue=tapi_default"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - '${APP_DOMAIN}:host-gateway'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '../packages/textract-laravel:/var/www/html'
      - '../packages/textract-core:/var/www/textract-core'
      - '../packages/textract-routing:/var/www/textract-routing'
    networks:
      - sail
    depends_on:
      - mysql
      - redis
      - mailpit
      - rabbitmq
    links:
      - rabbitmq
      - mysql
      - redis
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - sail
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq/rabbit.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - '${FORWARD_RABBIT_PORT:-15672}:15672'
      - '${FORWARD_RABBIT_DASHBOARD_PORT:-5672}:5672'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local