name: "PHPCS Routing"

on: [push, pull_request]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer, cs2pr

      - name: Install Composer
        run: cd packages/textract-routing && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Detect coding standard violations
        run: cd packages/textract-routing && ./vendor/bin/phpcs src/ --standard=ruleset.xml